use_frameworks!

platform :ios, '8.0'

target 'DXBaseViewControllerKit_Example' do
  pod 'DXBaseViewControllerKit', :path => '../'

  target 'DXBaseViewControllerKit_Tests' do
    inherit! :search_paths

    
  end
end
